version: '3'
services:
  database:
    image: mysql/mysql-server:8.0
    ports:
      - '3310:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'pokemon'
      MYSQL_USER: 'pokemonuser'
      MYSQL_PASSWORD: 'password'
    volumes:
      - './database:/var/lib/mysql'
